#Lists





In [ ]:
#structure of a list
lista = [1,2,3,4,5,6]

#lists inside lists are allowed
lista2 = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
# we can use [index] to consult a specific item from the list
lista2[1][2]

6

In [ ]:
#the append() function 
lista.append(lista2)
lista

[1, 2, 3, 4, 5, 6, [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

#Type

In [ ]:
type(lista2)

list

In [ ]:
#transforming int in float
float(lista2[2][1])


8.0

In [ ]:
#transforming float in int
int(lista2[2][1])

8

In [ ]:
#transforming the whole list into float
lista3 = [2, 4 , 10, 6]
c=0

for item in lista3:
  lista3[c] = float(item)
  c += 1

lista3

[2.0, 4.0, 10.0, 6.0]

In [ ]:
#transforming the whole list into float
lista4 = [2, 4 , 10, 6]
lista5 = []
for y in lista4:
    lista5.append(float(y))

print(lista5)

[2.0, 4.0, 10.0, 6.0]


#Tuple

Tuples are immutable lists, they doesn't support item assignment

In [ ]:
#structure of a tuple
tupla = (6,2,5)
tupla[2]

5

In [ ]:
#permanent data, does not support item assigment nor deletion
tupla[2] = 30
del tupla[2]

In [ ]:
#transforming lists into tuple
tupla2 = tuple(lista4)
print(tupla2)
type(tupla2)

(2, 4, 20, 6)


tuple

In [ ]:
#for python to identify a tuple, there must be at least a comma in the parenteses
tupla3 = (3)
print(type(tupla3))

tupla4 = (3,)
print(type(tupla4)

<class 'int'>
<class 'tuple'>


#Data Dictionary

In [ ]:
#structure of  dictionary 
# -> dicionario = {key:value}

dicionario = {'nome' : 'Marcos',
              'telefone' : '21 991069273',
              'endereço':'Rua Jorge Jose Duayer'}

In [ ]:
print("as chaves são:", dicionario.keys())
print("os valores são:", dicionario.values())
print("o dicionário contém:", dicionario.items())

as chaves são: dict_keys(['nome', 'telefone', 'endereço'])
os valores são: dict_values(['Marcos', '21 991069273', 'Rua Jorge Jose Duayer'])
o dicionário contém: dict_items([('nome', 'Marcos'), ('telefone', '21 991069273'), ('endereço', 'Rua Jorge Jose Duayer')])


In [ ]:
#adding data into a dictionary
dicionario['cor favorita'] = 'preto'

In [ ]:
dicionario.items()

dict_items([('nome', 'Marcos'), ('telefone', '21 991069273'), ('endereço', 'Rua Jorge Jose Duayer'), ('cor favorita', 'preto')])

In [ ]:
dicionario.clear()

In [ ]:
endereco = dicionario['endereço']
print(endereco)

Rua Jorge Jose Duayer


#Manipulating strings

In [ ]:
frase = 'Python é irado'

In [ ]:
# consulting structure [first character : last character : step]
frase[5:12:2]

'néia'

In [ ]:
#counting how many 'o' characters there are in frase
frase.count('o')

2

In [ ]:
len(frase)

14

In [ ]:
frase.replace('irado', 'maneiro') #only returns the new value, doesn't replace it in frase

'Python é maneiro'

#Lambda Function

The most general way to create a function is through `def` command

In [ ]:
def somaQuadrados (a,b):
  somaQ = a**2 + b**2
  return somaQ

In [ ]:
somaQuadrados(2,3)

13

The Lambda command can create the same function with less coding required

In [ ]:
# structure of labda functions: lambda parameter1, parameter2, parameter3: function
somaQuadrados2 = lambda a,b: a**2 + b**2

In [ ]:
somaQuadrados2(2,3)

13

# MAP()

Applies an action to each element in a object

In [ ]:
kmh = [23,5,54,87,4,26,85,458,25,578,94]

In [ ]:
#converting km/h to mph
mph = list(map(lambda x: x*0.62,kmh))
print(mph)

[14.26, 3.1, 33.48, 53.94, 2.48, 16.12, 52.7, 283.96, 15.5, 358.36, 58.28]


#List Comprehension

In [ ]:
mph2 = [x*0.62 for x in kmh]
print(mph2)

[14.26, 3.1, 33.48, 53.94, 2.48, 16.12, 52.7, 283.96, 15.5, 358.36, 58.28]


In [ ]:
caracteres = [x for x in "Coe, Rapaziada"]
print(caracteres)

['C', 'o', 'e', ',', ' ', 'R', 'a', 'p', 'a', 'z', 'i', 'a', 'd', 'a']


#Numpy

In [ ]:
import numpy as np

In [ ]:
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
c = np.zeros((4,3))

#c = np.ones((4,3))

print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#ID
c = np.eye(4)

print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
a.max()

9

In [ ]:
a.min()

1

In [ ]:
a.mean()

5.0

In [ ]:
a.std()

2.581988897471611

#Opening Files in the notebook

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel('C:/Users/ticom/Downloads/Controde de Estudos.xlsx') #in a local notebook

In [ ]:
from google.colab import files
import io

uploaded = files.upload()
df1 = pd.read_excel(io.BytesIO(uploaded['Controle de Estudos.xlsx']),header=1)

Saving Controle de Estudos.xlsx to Controle de Estudos (3).xlsx


In [ ]:
df1.head(2)

Dia  ...                                        Unnamed: 10
0 2021-06-08  ...  O curso completo de Banco de Dados e SQL, sem ...
1 2021-06-09  ...  O curso completo de Banco de Dados e SQL, sem ...

[2 rows x 11 columns]

#Pandas

In [ ]:
import pandas as pd

Pandas allow us to treat information as a dataframe


In [21]:
#creating a dictionary for the example
alunos_dic = {'nome': ['ricardo', 'paulo', 'gustavo', 'julia'],
              'nota': [4,7,5.5,9],
              'aprovado': ['não', 'sim', 'não', 'sim']}
print(alunos_dic)

{'nome': ['ricardo', 'paulo', 'gustavo', 'julia'], 'nota': [4, 7, 5.5, 9], 'aprovado': ['não', 'sim', 'não', 'sim']}


In [22]:
#the method pd.DataFrame() transforms the object into a dataframe
alunos_df = pd.DataFrame(alunos_dic)

In [ ]:
#method pd.Series() create a unidirectional vector with index
objeto1 = pd.Series([8,5,4,7,6,75])
print(objeto1)

0     8
1     5
2     4
3     7
4     6
5    75
dtype: int64


In [ ]:
objeto2 = np.array([1,2.3,9])
print('array:',objeto2)

#pd.Series() can transform a np.array 
objeto3 = pd.Series(objeto2)
print("""
serie:

""", objeto3)

array: [1.  2.3 9. ]

serie:

 0    1.0
1    2.3
2    9.0
dtype: float64


In [ ]:
alunos_df.shape

(4, 3)

In [ ]:
alunos_df.describe()

##Manipulating rows

In [ ]:
alunos_df.loc[2]

nome        gustavo
nota            5.5
aprovado        não
Name: 2, dtype: object

In [ ]:
alunos_df.loc[[2]]

nome  nota aprovado
2  gustavo   5.5      não

In [ ]:
alunos_df.loc[0:1]

nome  nota aprovado
0  ricardo   4.0      não
1    paulo   7.0      sim

In [ ]:
alunos_df.loc[alunos_df['nome']=='julia']

nome  nota aprovado
3  julia   9.0      sim

In [23]:
alunosreprovados = alunos_df.loc[alunos_df['nota'] !=9 ]
print(alunosreprovados)

      nome  nota aprovado
0  ricardo   4.0      não
1    paulo   7.0      sim
2  gustavo   5.5      não


In [24]:
alunosreprovados2 = alunos_df.loc[alunos_df['nota'] <=6]
print(alunosreprovados2)

      nome  nota aprovado
0  ricardo   4.0      não
2  gustavo   5.5      não


In [ ]:
#counting rows
len(alunos_df)

##Manipulating columns

In [ ]:
alunos_df['nome']

0    ricardo
1      paulo
2    gustavo
3      julia
Name: nome, dtype: object

In [26]:
#defing a var with a column return a pandas.Series type
notas = alunos_df['nota']
print(notas, type(notas))

0    4.0
1    7.0
2    5.5
3    9.0
Name: nota, dtype: float64 <class 'pandas.core.series.Series'>


In [31]:
#counting values
alunos_df['aprovado'].value_counts()

não    2
sim    2
Name: aprovado, dtype: int64

###Renaming columns

In [ ]:
alunos_df1 = alunos_df.rename(columns={'nome' : 'Alunos','nota': 'Nota', 'aprovado': 'Aprovado'})

###Deleting columns (drop())

In [39]:
alunos_df1.drop('Aprovado', axis = 1)

Alunos  Nota
0  ricardo   4.0
1    paulo   7.0
2  gustavo   5.5
3    julia   9.0

##Dealing with NaN

In [ ]:
# Dropna() deletes the rows with NaN cells
df.dropna()

In [ ]:
#isnull() returns a df with "True" ans "False" information if each cell contains NaN values
enulo = df.isnull() 

# sum() here act as an aggregate function, returning how many fields of each column is NaN
faltantes = df.isnull().sum()

# we can see how much (%) of each column is missing 
faltantes_percentual = (df.isnull().sum() / len(df.iloc[:,0])*100

In [ ]:
# fillna() fills the NaN fields, in this example, with the mean value for the column in question
df['col_data'].fillna(df['col_data'].means(), inplace = True)

# filling NaN fields with 0
df['col2_data'].fillna(0, inplace = True)

# Input

In [57]:
a = input("digita coisa aí: ")
a

digita coisa aí: tico


'tico'