<a href="https://colab.research.google.com/github/marcos-mansur/my-study-notes/blob/main/Python_study_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Lists





In [ ]:
#structure of a list
lista = [1,2,3,4,5,6]

#lists inside lists are allowed
lista2 = [[1,2,3],[4,5,6],[7,8,9]]

##select data

In [ ]:
# we can use [index] to consult a specific item from the list
lista2[1][2]

6

In [ ]:
# we can use negative index to reference the end of a list
lista2[-2]

[4, 5, 6]

## Slicing lists

In [ ]:
players = ['jorge', 'miguel', 'carolina', 'carlos', 'douglas']

#slices are groups of items
print(players[1:3])

print(players[:3]) #if we omit the first term, it starts at the beginning

print(players[2:]) #if we omit the last term, it will go until the end

print(players[-2:]) 

['miguel', 'carolina']
['jorge', 'miguel', 'carolina']
['carolina', 'carlos', 'douglas']
['carlos', 'douglas']


## add data

In [ ]:
#the append() function add data to the end of the list
lista.append(lista2)
lista

In [ ]:
# we can insert data in any position
lista.insert(3,27)
lista

[1, 2, 3, 27, 4, 5, 6]

## remove data

In [ ]:
#delete data in a list by index
del lista[3]
lista

[1, 2, 3, 4, 5, 6]

In [ ]:
#cut an item by index
popped_lista = lista.pop(3)
print(lista)
print(popped_lista)

[1, 2, 3, 5, 6]
4


In [ ]:
#remove() can remove an item by value, but only the first ocurrency. A for-loop can work around this
lista1 = ['carro', 'cachorro', 'moto', 'bike', 'cachorro', 'onibus', 'cachorro']
c = 'cachorro'
for x in lista1:
  if c in lista1:
    lista1.remove('cachorro')

lista1

['carro', 'moto', 'bike', 'onibus']

##Sort the list

In [ ]:
#sort() method sorts a list permanently 
lista1.sort(reverse=True)
print(lista1)

#reverse() reverses the original order, but doesn't sort

['onibus', 'moto', 'carro', 'bike']

In [ ]:
#sorted() method sorts a list for display but doesn't affect the object
print(sorted(lista1))

['bike', 'carro', 'moto', 'onibus']


##Making numerical lists

In [ ]:
lista5 = list(range(2,9))
print(lista5)

lista6 = list(range(5,26,3))
print(lista6)

[2, 3, 4, 5, 6, 7, 8]
[5, 8, 11, 14, 17, 20, 23]


##Copying a list

In [ ]:
lista_x = ['feijão', 'batata', 'brócolis', 'couve', 'couve-flor']

# the following line of code doesn't make a copy of lista_x. 
# Insetead, it tells python to associate "lista_z" with the same list that "lista_x" is associated to
lista_z = lista_x      #so now, both variables points to the same list


lista_x.append('cenoura')

print(lista_z)

['feijão', 'batata', 'brócolis', 'couve', 'couve-flor', 'cenoura']


In [ ]:
# for actually copying a list, we need to use a slice
lista_z = lista_x[:]

#Set
a set is a collection in which each item must be unique


In [ ]:
lista7 = ['cachorro', 'cavalo', 'cachorro', 'gato']

#set() method returns unique values
print(set(lista7))

{'cachorro', 'cavalo', 'gato'}


In [ ]:
# a set can be defined by {} separetad by commas

set1 = {'cachorro', 'cavalo', 'cachorro', 'gato'}
set1

{'cachorro', 'cavalo', 'gato'}

#List Comprehension

In [ ]:
mph2 = [x*0.62 for x in kmh]
print(mph2)

[14.26, 3.1, 33.48, 53.94, 2.48, 16.12, 52.7, 283.96, 15.5, 358.36, 58.28]


In [ ]:
caracteres = [x for x in "Coe, Rapaziada"]
print(caracteres)

['C', 'o', 'e', ',', ' ', 'R', 'a', 'p', 'a', 'z', 'i', 'a', 'd', 'a']



#Type

In [ ]:
type(lista2)

list

In [ ]:
#transforming int in float
float(lista2[2][1])


8.0

In [ ]:
#transforming float in int
int(lista2[2][1])

8

In [ ]:
#transforming the whole list into float
lista3 = [2, 4 , 10, 6]
c=0

for item in lista3:
  lista3[c] = float(item)
  c += 1

lista3

[2.0, 4.0, 10.0, 6.0]

In [ ]:
#transforming the whole list into float
lista4 = [2, 4 , 10, 6]
lista5 = []
for y in lista4:
    lista5.append(float(y))

print(lista5)

[2.0, 4.0, 10.0, 6.0]


#Tuple

Tuples are immutable lists, they doesn't support item assignment

In [ ]:
#structure of a tuple
tupla = (6,2,5)
tupla[2]

5

In [ ]:
#permanent data, does not support item assigment nor deletion
tupla[2] = 30
del tupla[2]

In [ ]:
#transforming lists into tuple
tupla2 = tuple(lista4)
print(tupla2)
type(tupla2)

(2, 4, 20, 6)


tuple

In [ ]:
#for python to identify a tuple, there must be at least a comma in the parenteses
tupla3 = (3)
print(type(tupla3))

tupla4 = (3,)
print(type(tupla4)

<class 'int'>
<class 'tuple'>


#Data Dictionary

In [ ]:
#structure of  dictionary 
# -> dicionario = {key:value}

dicionario = {'nome' : 'Marcos',
              'telefone' : '21 991069273',
              'endereço':'Rua Jorge Jose Duayer',
              'apagar' : 'apagar essa linha'}

In [ ]:
dicionario['nome']

'Marcos'

In [ ]:
print("as chaves são:", dicionario.keys())
print("os valores são:", dicionario.values())
print("o dicionário contém:", dicionario.items())

as chaves são: dict_keys(['nome', 'telefone', 'endereço'])
os valores são: dict_values(['Marcos', '21 991069273', 'Rua Jorge Jose Duayer'])
o dicionário contém: dict_items([('nome', 'Marcos'), ('telefone', '21 991069273'), ('endereço', 'Rua Jorge Jose Duayer')])


##Select data

In [ ]:
#select data
endereco = dicionario['endereço']
print(endereco)

Rua Jorge Jose Duayer


In [ ]:
#looping through all values of a dictionary
for key, value in dicionario.items():
    print(key.title(),':',value.upper())

Nome : MARCOS
Telefone : 21 991069273
Endereço : RUA JORGE JOSE DUAYER
Cor Favorita : PRETO


## Add data

In [ ]:
#adding data into a dictionary
dicionario['cor favorita'] = 'preto'

##Delete data

In [ ]:
#deleting all data in a dictionary
dicionario.clear()

In [ ]:
#delete a key:value pair
del dicionario['apagar']
print(dicionario)

{'nome': 'Marcos', 'telefone': '21 991069273', 'endereço': 'Rua Jorge Jose Duayer', 'cor favorita': 'preto'}


## Get()

In [ ]:
#the get() method can be useful for when you're not sure if the key you are consulting actually exist
carro = dicionario.get('carro', "sem valor atribuído para carro")

print(carro)

sem valor atribuído para carro


 # Manipulating strings

In [ ]:
frase = 'Python é irado'

In [ ]:
# consulting structure [first character : last character : step]
frase[5:12:2]

'néia'

In [ ]:
#counting how many 'o' characters there are in frase
frase.count('o')

2

In [ ]:
len(frase)

14

In [ ]:
frase.replace('irado', 'maneiro') #only returns the new value, doesn't replace it in frase

'Python é maneiro'

#Lambda Function

The most general way to create a function is through `def` command

In [ ]:
def somaQuadrados (a,b):
  somaQ = a**2 + b**2
  return somaQ

In [ ]:
somaQuadrados(2,3)

13

The Lambda command can create the same function with less coding required

In [ ]:
# structure of labda functions: lambda parameter1, parameter2, parameter3: function
somaQuadrados2 = lambda a,b: a**2 + b**2

In [ ]:
somaQuadrados2(2,3)

13

# MAP()

Applies an action to each element in a object

In [ ]:
kmh = [23,5,54,87,4,26,85,458,25,578,94]

#converting km/h to mph
mph = list(map(lambda x: x*0.62,kmh))
print(mph)

[14.26, 3.1, 33.48, 53.94, 2.48, 16.12, 52.7, 283.96, 15.5, 358.36, 58.28]


#Numpy

In [ ]:
import numpy as np

In [ ]:
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
c = np.zeros((4,3))

#c = np.ones((4,3))

print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#ID
c = np.eye(4)

print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
a.max()

9

In [ ]:
a.min()

1

In [ ]:
a.mean()

5.0

In [ ]:
a.std()

2.581988897471611

#Opening Files in the notebook

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel('C:/Users/ticom/Downloads/Controde de Estudos.xlsx') #in a local notebook

In [ ]:
from google.colab import files
import io

uploaded = files.upload()
df1 = pd.read_excel(io.BytesIO(uploaded['Controle de Estudos.xlsx']),header=1)

Saving Controle de Estudos.xlsx to Controle de Estudos (3).xlsx


In [ ]:
df1.head(2)

Dia  ...                                        Unnamed: 10
0 2021-06-08  ...  O curso completo de Banco de Dados e SQL, sem ...
1 2021-06-09  ...  O curso completo de Banco de Dados e SQL, sem ...

[2 rows x 11 columns]

#Pandas

In [ ]:
import pandas as pd

Pandas allow us to treat information as a dataframe


In [ ]:
#creating a dictionary for the example
alunos_dic = {'nome': ['ricardo', 'paulo', 'gustavo', 'julia'],
              'nota': [4,7,5.5,9],
              'aprovado': ['não', 'sim', 'não', 'sim']}
print(alunos_dic)

{'nome': ['ricardo', 'paulo', 'gustavo', 'julia'], 'nota': [4, 7, 5.5, 9], 'aprovado': ['não', 'sim', 'não', 'sim']}


In [ ]:
#the method pd.DataFrame() transforms the object into a dataframe
alunos_df = pd.DataFrame(alunos_dic)

In [ ]:
#method pd.Series() create a unidirectional vector with index
objeto1 = pd.Series([8,5,4,7,6,75])
print(objeto1)

0     8
1     5
2     4
3     7
4     6
5    75
dtype: int64


In [ ]:
objeto2 = np.array([1,2.3,9])
print('array:',objeto2)

#pd.Series() can transform a np.array 
objeto3 = pd.Series(objeto2)
print("""
serie:

""", objeto3)

array: [1.  2.3 9. ]

serie:

 0    1.0
1    2.3
2    9.0
dtype: float64


In [ ]:
alunos_df.shape

(4, 3)

In [ ]:
alunos_df.describe()

nota
count  4.000000
mean   6.375000
std    2.136001
min    4.000000
25%    5.125000
50%    6.250000
75%    7.500000
max    9.000000

In [ ]:
alunos_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   nome      4 non-null      object 
 1   nota      4 non-null      float64
 2   aprovado  4 non-null      object 
dtypes: float64(1), object(2)
memory usage: 224.0+ bytes


##Manipulating rows

In [ ]:
alunos_df.loc[2]

nome        gustavo
nota            5.5
aprovado        não
Name: 2, dtype: object

In [ ]:
alunos_df.loc[[2]]

nome  nota aprovado
2  gustavo   5.5      não

In [ ]:
alunos_df.loc[0:1]

nome  nota aprovado
0  ricardo   4.0      não
1    paulo   7.0      sim

In [ ]:
alunos_df.loc[alunos_df['nome']=='julia']

nome  nota aprovado
3  julia   9.0      sim

In [ ]:
alunosreprovados = alunos_df.loc[alunos_df['nota'] !=9 ]
print(alunosreprovados)

      nome  nota aprovado
0  ricardo   4.0      não
1    paulo   7.0      sim
2  gustavo   5.5      não


In [ ]:
alunosreprovados2 = alunos_df.loc[alunos_df['nota'] <=6]
print(alunosreprovados2)

      nome  nota aprovado
0  ricardo   4.0      não
2  gustavo   5.5      não


In [ ]:
#counting rows
len(alunos_df)

##Manipulating columns

In [ ]:
alunos_df['nome']

0    ricardo
1      paulo
2    gustavo
3      julia
Name: nome, dtype: object

In [ ]:
#defing a var with a column return a pandas.Series type
notas = alunos_df['nota']
print(notas, type(notas))

0    4.0
1    7.0
2    5.5
3    9.0
Name: nota, dtype: float64 <class 'pandas.core.series.Series'>


In [ ]:
#counting values
alunos_df['aprovado'].value_counts()

não    2
sim    2
Name: aprovado, dtype: int64

###Renaming columns

In [ ]:
alunos_df1 = alunos_df.rename(columns={'nome' : 'Alunos','nota': 'Nota', 'aprovado': 'Aprovado'})

###Deleting columns (drop())

In [ ]:
alunos_df1.drop('Aprovado', axis = 1)

Alunos  Nota
0  ricardo   4.0
1    paulo   7.0
2  gustavo   5.5
3    julia   9.0

##Dealing with NaN

In [ ]:
import missingno as msno
msno.matrix(df)

In [ ]:
# Dropna() deletes the rows with NaN cells
df.dropna()

In [ ]:
#isnull() returns a df with "True" and "False" if each field contains NaN values
enulo = df.isnull() 

# sum() here act as an aggregate function, returning how many fields of each column is NaN
faltantes = df.isnull().sum()

# we can see how much (%) of each column is missing 
faltantes_percentual = (df.isnull().sum() / len(df.iloc[:,0])*100)

In [ ]:
# fillna() fills the NaN fields, in this example, with the median value for the column in question
df['col_name'].fillna(df['col_name'].median(axis=0), inplace = True)

# filling NaN fields with 0
df['col2_data'].fillna(0, inplace = True)

# Input

input() always return a str. If you want to make numerical comparisons, use int() to transform the input

In [ ]:
a = input("digita coisa aí: ")
a

digita coisa aí: tico


'tico'

#Flag

for a program that should run as long as many conditions are true, you can define a single variable that determines whether or not the entire program is active

In [ ]:
active = True     # when the flag named active turns to false, 
while active:     # the program will finish the code and close without any further loops
  message = input("\nwhat's you name? ")

  if message == 'quit':
    active = False
  else:
    print("Hi, {}!".format(message))

print('by!')


what's you name? tico
Hi, tico!

what's you name? quit
by!


In [ ]:
active = True
while active:
  topping = input("\nWhat topping do you want: ")
  
  if topping == 'quit':
    active = False
  else:
    print(f"we're adding {topping.title()} to your order!")


What topping do you want: brocoli
we're adding Brocoli to your order!

What topping do you want: quit


#Break and Continue

to exit a `while` loop immediately without running any remaining code in the loop, we can use `break` statement

Rather than breaking the loop, `continue`tells python to ignore the rest of the code block inside a loop and go back to the start of the loop

In [ ]:
#Break example
while True:
  city = input('\nWhere are you from? ')

  if city == 'quit':
    break
    print('by!') #this line won't be read by python because it's after a break
  else:
    print(f"I'd love to go to {city.title()}")


Where are you from? Manhumirim
I'd love to go to Manhumirim

Where are you from? quit


In [ ]:
#Continue Example
current_number = 0
odd_numbers_list = []

last_odd1 = input('odd numbers until: \n')

while current_number < int(last_odd1):
  current_number += 1
  if current_number % 2 ==0:
    continue
    print("laláaaa")  #this line of code won't be read by python because it's after continue in same identation

  odd_numbers_list.append(current_number)

print(odd_numbers_list)

odd numbers until: 
15
[1, 3, 5, 7, 9, 11, 13, 15]


#Functions

There are 3 types of arguments:
- Positional argument
- keyword argument
- lists, dictionarys and values

When using default values, any parameter with a default value needs to be listed after all the parameters thar don't have dafault values. This allows python to continue interpreting posicional arguments correctly

#Class

In [ ]:
class Car:

  def __init__(self, model, maker, year):
    """initialize atributes to describe a car"""
    self.model = model
    self.maker = maker
    self.year = year
    self.odometer_reading = 0  #default value of 0
  
  def get_descriptive_name(self):
    """returns a mneatly formatted descriptive name"""
    long_name = f'{self.year} {self.maker} {self.model}'
    return long_name.title()
  
  def read_odometer(self):
    """print a statement showing the car's mileage"""
    print(f'this car has {self.odometer_reading} miles on it')

  def update_odometer(self, mileage):
    """
    set the odometer reading to the given value
    if the new value is higher than the previous
    """
    if mileage >= self.odometer_reading:
      self.odometer_reading = mileage
    else:
      print("don't you dare to roll back that odemeter! \n")
  
  def increase_odometer(self, miles):
    """ increase the odometer reading"""
    if miles > 0:
      self.odometer_reading += miles
    else:
      print("don't you dare to roll back that odemeter! \n")

In [ ]:
my_new_car= Car('a4','audi', 2019)
print(my_new_car.get_descriptive_name())
my_new_car.read_odometer()

2019 Audi A4
this car has 0 miles on it



##Attributes

In [ ]:
#modifying attribute values directy
my_new_car.odometer_reading = 23
my_new_car.read_odometer()

this car has 23 miles on it


In [ ]:
#modifying attribute value through a method()
my_new_car.update_odometer(36)
my_new_car.read_odometer()

print(""" 
""")

#testing rolling back the odemeter
my_new_car.update_odometer(22)
my_new_car.read_odometer()


this car has 36 miles on it
 

don't you dare to roll back that odemeter! 

this car has 36 miles on it


In [ ]:
my_new_car.increase_odometer(23000)
my_new_car.read_odometer()

this car has 23036 miles on it


In [ ]:
<img src="//imgs.xkcd.com/comics/houseguests.png" title="You can come on in, we're all fully vaccinated. Except the spare room off the living room. Don't go in there, we're not fully vaccinated in there." alt="Houseguests" srcset="//imgs.xkcd.com/comics/houseguests_2x.png 2x" style="image-orientation:none">

#Boxplot

In [ ]:
df.boxplot(column = 'coluna')